import { supabaseClient } from '../config.js';
import { state } from '../core/state.js';
import { initGenericImageDropzone, syncGenericDropzoneState } from '../core/storage.js';
import { safeUrl, showToast } from '../core/utils.js';
import { attachMediaPickerButton } from './media-library.js';
function preview(box,url,fallback,alt=''){if(!box)return;const safe=safeUrl(url);box.replaceChildren();if(!safe){box.textContent=fallback;return;}const img=document.createElement('img');img.src=safe;img.alt=alt;img.loading='lazy';img.addEventListener('error',()=>box.textContent=fallback,{once:true});box.appendChild(img);}
export function applyFavicon(url){const safe=safeUrl(url);let link=document.querySelector("link[rel~='icon'][data-custom-favicon]");if(!safe){link?.remove();return;}if(!link){link=document.createElement('link');link.rel='icon';link.dataset.customFavicon='true';document.head.appendChild(link);}link.href=safe;}
export function applySiteLogo(url){const safe=safeUrl(url),imgs=[...document.querySelectorAll('.js-site-logo-image')],falls=[...document.querySelectorAll('.js-site-logo-fallback')];const fallback=()=>{imgs.forEach(i=>i.classList.add('hidden'));falls.forEach(f=>f.classList.remove('hidden'));};imgs.forEach(img=>{img.onerror=fallback;if(safe){img.src=safe;img.classList.remove('hidden');}else{img.removeAttribute('src');img.classList.add('hidden');}});falls.forEach(f=>f.classList.toggle('hidden',!!safe));}
export function populateFaviconForm(){const fi=document.getElementById('favicon-image-input'),fp=document.getElementById('favicon-preview'),li=document.getElementById('site-logo-image-input'),lp=document.getElementById('site-logo-preview');if(fi)fi.value=state.faviconUrl||'';if(li)li.value=state.siteLogoUrl||'';syncGenericDropzoneState('favicon',state.faviconUrl||'');syncGenericDropzoneState('site-logo',state.siteLogoUrl||'');preview(fp,state.faviconUrl,'?','Favicon actual');preview(lp,state.siteLogoUrl,'⚔','Logo actual');}
async function saveIcons(){const box=document.getElementById('favicon-config-error'),f=document.getElementById('favicon-image-input')?.value.trim()||'',l=document.getElementById('site-logo-image-input')?.value.trim()||'';box?.classList.add('hidden');if(!state.adminCode){if(box){box.textContent='Tu sesión de administrador expiró.';box.classList.remove('hidden');}return;}const [a,b]=await Promise.all([supabaseClient.rpc('update_app_setting',{input_code:state.adminCode,input_key:'favicon_url',input_value:f}),supabaseClient.rpc('update_app_setting',{input_code:state.adminCode,input_key:'site_logo_url',input_value:l})]);const err=a.error||b.error;if(err){if(box){box.textContent=`Error: ${err.message}`;box.classList.remove('hidden');}return;}state.faviconUrl=f;state.siteLogoUrl=l;applyFavicon(f);applySiteLogo(l);populateFaviconForm();showToast('Iconos del sitio guardados','success');}
export function initFaviconTool(){const fi=document.getElementById('favicon-image-input'),fp=document.getElementById('favicon-preview'),li=document.getElementById('site-logo-image-input'),lp=document.getElementById('site-logo-preview');if(!fi)return;document.getElementById('favicon-save-btn')?.addEventListener('click',saveIcons);document.getElementById('favicon-clear-btn')?.addEventListener('click',()=>{fi.value='';syncGenericDropzoneState('favicon','');preview(fp,'','?');applyFavicon('');});document.getElementById('site-logo-clear-btn')?.addEventListener('click',()=>{if(li)li.value='';syncGenericDropzoneState('site-logo','');preview(lp,'','⚔');applySiteLogo('');});initGenericImageDropzone('favicon','favicons',()=>state.faviconUrl||'',url=>{preview(fp,url,'?','Favicon');applyFavicon(url);});if(li)initGenericImageDropzone('site-logo','branding',()=>state.siteLogoUrl||'',url=>{preview(lp,url,'⚔','Logo');applySiteLogo(url);});attachMediaPickerButton({targetInputId:'favicon-image-input',insertAfterId:'favicon-dropzone',title:'Seleccionar favicon',onSelect:({url})=>{preview(fp,url,'?','Favicon');syncGenericDropzoneState('favicon',url);applyFavicon(url);}});if(li)attachMediaPickerButton({targetInputId:'site-logo-image-input',insertAfterId:'site-logo-dropzone',title:'Seleccionar logo del sitio',onSelect:({url})=>{preview(lp,url,'⚔','Logo');syncGenericDropzoneState('site-logo',url);applySiteLogo(url);}});populateFaviconForm();}
